### ISSUE TITLE
stack as a first reduce function

### ISSUE THREAD

**Issue by pavlis** [wangyinz/mspass#71] opened 2020-10-12 18:36 UTC
In our weekly conference call last week we discussed implementing what we call "stacking" = averaging = summation as an definitive example of a reduce operator in MsPASS.   It clearly fits the model as a type example shown in the spark documentation is add of a set of simple numbers.  A simple stack does exactly that but just adding vectors (TimeSeries) or matrices (Seismogram) instead of simple numbers.   

I'm definitely compromised here by never having done more than read about reduce operations  before.   However, first off I think stacking could and should be implemented in two forms:
1.  The spark reduce operation with a sum operator defined (more on that in a second).   In my reading a natural way to do that is actually with the reduceByKey method with the key being pulled from metadata.  e.g. one might used "evid" as a key for stacking by event.   
2.  There is also an obvious map function that behaves like reduce.  That is, we can and construct a stack_ensemble function that maps ensemble data to a single Seismogram or TimeSeries output.  That is not a reduce operation but map as I understand it.  It might be a useful comparison to see how the two algorithms compare on benchmarks.   From what I read they would definitely be handled differently.

For the reduce operator from my reading I think the right approach is actually not to do this with numpy but use operator+ defined for TimeSeries and Seismogram objects.   The first is already (almost) there for CoreTimeSeries (I see only operator+=) and the second would be trivial to implement.   The main addition is we would need to build operator+ for the top level Seismogram and TimeSeries objects that would properly handle errors and post them to elog and never abort.  At least from what I can tell the binary function required for a reduce, like map, must never ever throw an unhandled exception or the job will abort.  I'm pretty sure that is true, but that is readily handled by defining operator+ for TimeSeries and Seismogram where errors can be posted to elog.   These operators would also have to define the history data.  Either way my misunderstanding of how reduce worked may require some changes to the history api to allow the sequential accumulation that is used by reduce - I didn't realize that when we developed that stuff.

On the other hand, the python alternative remains an option.  In many ways the logic of the function is identical.  Do we want to do this in python just to use it as an example of how to do a reduce operator?   The level of development and lines of code are probably similar with either model.   Could even do both and use them as benchmarks for the two approaches.  My guess, however, is that they won't differ a lot and it is a pretty esoteric issue that wouldn't help much in either selling MsPASS to the community or in our development - the things it tests are subtle.

**Comment by wangyinz** [comment] 2020-10-12 20:40
I think we should just do it in Python as an example, and it shouldn't make any noticeable difference performance-wise. 

A comment on the history API: I agree that it will make the interface cleaner by enabling accumulation over reduce. I was only thinking appending the history record afterwards as a separate function call, but I can see now that it will be a confusing interface.

**Comment by pavlis** [comment] 2020-10-13 10:06
Ok, will proceed to build this in python.   Probably a useful way for me to better understand spark anyway.   Have been reading lots of web tutorials on the topic.  I next need an example of reduce applied to something more complicated than a standard type and a more complicated example where the function called is not a lamba function.  As is typical of tutorials google tends to give you the most popular ones which are the most basic.  Good to start, but I'm now past that.   I'll keep digging but if you have a good example please post a link here.

Absolutely correct that new_reduce in history needs a new name - new_accumulator is probably the right name.   Note there is already the function we need for this context called add_one_input defined for ProcessingHistory.   A further complication I realized this morning in reading spark's documentation is that the left hand side of the thing  being accumulated has to be initialized in a global.  i.e. a consequence of the associative  requirement for a reduce opeation is we may need a way to merge history chains accumulated in calls to add_one_input in different process chains from through different processors.  Said another way, ProcessingHistory is not associative without some mechanism to handle that.   Right now I don't know for sure what that is.

**Comment by pavlis** [comment] 2020-10-14 10:45
Thought about this some more yesterday in the long drive from NY to central Ohio.   I've come to realize that there are very few existing seismic processing algorithms that match the restrictions of reduce.   As noted above even stack has some complications.   All examples I can think of could be implemented as map operators on ensembles more easily and with fewer complications.  If you can think of an example to the contrary I'd like to hear it.  Maybe there are examples in machine learning, but I don't know enough about the details of those methods to know.  

My conclusion is I think I will implement both a "stack" and "stack_ensemble" function.  The first will be a reduce operator and the second a map operator.  We can and use them in a documentation page to show cautions in implementing reduce operators.

**Comment by JiaoMaWHU** [comment] 2020-10-14 15:40
Hey Gary, I'm not quite following here. 

Let's say we have a spark RDD like this
`seis_list = RDD([seis1, seis2, seis3, ...])`
, then we do a reduce operation of stacking, then I think the stack operator you mentioned should be used like this,
`res = seis_list.reduce(lambda seis1, seis2: stack(seis1, seis2) )`

Did I get your point?

**Comment by wangyinz** [comment] 2020-10-14 17:54
Yes, I agree that most of the operations that we use are maps, and I think that's OK - we are going to support mostly maps, but also allow users to do reduce if needed. A plain stack is definitely a reduce, but I do think any sophisticated stacking can be decomposed into map, filter, and reduce. This way we are effectively reducing the granularity of parallelism. Whether a small granularity is good or not is something we can benchmark with, but our framework has the capability to do either no matter what.

Spend a little time thinking of the history mechanism, and I see what you mean about the new mechanism here. Actually, I found that the add_one_input is not really doing what we want here:
```
(Pdb) ste
ProcessingHistory({'status': ProcessingStatus.VOLATILE, 'uuid': '52c68e2c-0520-4890-a6d1-d29a1a97b2e6', 'algorithm': 'onetoone', 'algid': '0', 'stage': 1, 'type': AtomicType.SEISMOGRAM})
(Pdb) ste.get_nodes()
{'52c68e2c-0520-4890-a6d1-d29a1a97b2e6': [NodeData({'status': ProcessingStatus.RAW, 'uuid': 'fakeste_1', 'algorithm': 'fakedataset', 'algid': '0', 'stage': 0, 'type': AtomicType.SEISMOGRAM})]}

(Pdb) ph
ProcessingHistory({'status': ProcessingStatus.VOLATILE, 'uuid': '6e640c1a-f2fa-4ed4-a51e-07d4415b6e1e', 'algorithm': 'onetoone', 'algid': '0', 'stage': 1, 'type': AtomicType.SEISMOGRAM})
(Pdb) ph.get_nodes()
{'6e640c1a-f2fa-4ed4-a51e-07d4415b6e1e': [NodeData({'status': ProcessingStatus.RAW, 'uuid': 'fakeuuid1', 'algorithm': 'fakeinput', 'algid': '0', 'stage': 0, 'type': AtomicType.SEISMOGRAM})]}

(Pdb) ph.add_one_input(ste)
(Pdb) ph
ProcessingHistory({'status': ProcessingStatus.VOLATILE, 'uuid': '6e640c1a-f2fa-4ed4-a51e-07d4415b6e1e', 'algorithm': 'onetoone', 'algid': '0', 'stage': 1, 'type': AtomicType.SEISMOGRAM})
(Pdb) ph.get_nodes()
{'52c68e2c-0520-4890-a6d1-d29a1a97b2e6': [NodeData({'status': ProcessingStatus.RAW, 'uuid': 'fakeste_1', 'algorithm': 'fakedataset', 'algid': '0', 'stage': 0, 'type': AtomicType.SEISMOGRAM})], '6e640c1a-f2fa-4ed4-a51e-07d4415b6e1e': [NodeData({'status': ProcessingStatus.RAW, 'uuid': 'fakeuuid1', 'algorithm': 'fakeinput', 'algid': '0', 'stage': 0, 'type': AtomicType.SEISMOGRAM})]}
```
It did not create a new node under '6e640c1a-f2fa-4ed4-a51e-07d4415b6e1e' to associate it with '52c68e2c-0520-4890-a6d1-d29a1a97b2e6', which is what should be done for a reduce operation. Basically, we want the last output to be like this:
```
{'52c68e2c-0520-4890-a6d1-d29a1a97b2e6': [
   NodeData({'status': ProcessingStatus.RAW, 'uuid': 'fakeste_1', 'algorithm': 'fakedataset', 'algid': '0', 'stage': 0, 'type': AtomicType.SEISMOGRAM})], 
 '6e640c1a-f2fa-4ed4-a51e-07d4415b6e1e': [
   NodeData({'status': ProcessingStatus.RAW, 'uuid': 'fakeuuid1', 'algorithm': 'fakeinput', 'algid': '0', 'stage': 0, 'type': AtomicType.SEISMOGRAM}), 
   NodeData({'status': ProcessingStatus.VOLATILE, 'uuid': '52c68e2c-0520-4890-a6d1-d29a1a97b2e6', 'algorithm': 'onetoone', 'algid': '0', 'stage': 1, 'type': AtomicType.SEISMOGRAM})]}
```
So, we will need to fix the `add_one_input` first. But then, there is the question that how we can make this associative. Not quite sure about that yet, maybe we need to write a function to flatten the history records?

**Comment by pavlis** [comment] 2020-10-16 14:53
I believe I have a fix to this problem, but will need to do some testing to assure this works the way I think it should.

This is the revised api for reduce operators in spark (with comments as they currently stand):
```
/*! \brief Method to use with a spark reduce algorithm.

  A reduce operator in spark utilizes a binary function where two inputs
  are used to generate a single output object.   Because the inputs could be
  scattered on multiple processor nodes this operation must be associative.
  The new_ensemble_process method does not satisfy that constraint so this method
  was necessary to handle that type of algorithm correctly.

  The way this algorithm works is it fundamentally branches on two different
  cases: (1) initialization, which is detected by testing if the node data
  map is empty or (2) secondary calls.   This should work even if multiple
  inputs are combined at the end of the reduce operation because the copies
  being merged will not be empty.   Note an empty input will create a complaint
  entry in the error log.

  */
  void accumulate(const string alg,const string algid,
    const AtomicType typ,const ProcessingHistory& newinput);
  /* I think we need a method like this to solve the conflicting uuid
  problem.   Provided we guarantee alg and algid are unique this can just
  scan for maching alg and algid values and force constant uuids for the
  end of the chain.   
  */
  string clean_accumulate_uuids(const string alg, const string algid);
```
where I need to add the documentation for the arguments, but hopefully the usage is obvious as the names are the same as new_map and definitions are the same.  

For reference I changed the old new_reduction method to this:
```
  /*! Define history chain for an algorithm with multiple inputs in an ensemble.

  Use this method to define the history chain for an algorithm that has
  multiple inputs for each output.  Each output needs to call this method
  to build the connections that define how all inputs link to the the
  new data being created by the algorithm that calls this method.  Use this
  method for map operators that have an ensemble object as input and a single
  data object as output.  This method should be called in creation of the
  output object.  If the algorthm builds multiple outputs to build an
  output ensemble call this method for each output before pushing it to
  the output ensemble container.

  This method should not be used for a reduce operation in spark.  It does
  not satisfy the associative rule for reduce. Use accumulate for reduce
  operations.

  Normally, it makes sense to have the boolean create_newid true so it is
  guaranteed the current_id is unique.  There is little cost in creating a new
  one if there is any doubt the current_id is not a duplicate.  The false option
  is there only for rare cases where the current id value needs to be preserved.

  Note the vector of data passed is raw pointers for efficiency to avoid
  excessive copying.   For normal use this should not create memory leaks
  but make sure you don't try to free what the pointers point to or problems are
  guaranteed.  It is VERY IMPORTANT to realize that all the pointers are
  presumed to point to the ProcessingHistory component of a set of larger data
  object (Seismogram or TimeSeries).  The parents do not all have be a common
  type as if they have valid history data within them their current type
  will be defined.

  This method ALWAYS marks the status as VOLATILE.

  \param alg is the algorithm names to assign to the origin node.  This
    would normally be name defining the algorithm that makes sense to a human.
  \param algid is an id designator to uniquely define an instance of algorithm.
    Note that algid must itself be a unique keyword or the history chains
    will get scrambled.  alg is mostly carried as baggage to make output
    more easily comprehended without additional lookups.
  \param typ defines the data type (C++ class) the algorithm that is generating
    this data will create.
  \param create_newid is a boolean defining how the current id is handled.
    As described above, if true the method will call newid and set that
     as the current id of this data object.  If false the current value is
     left intact.
  \return a string representation of the uuid of the data to which this
    ProcessingHistory is now attached.
  */
  string new_ensemble_process(const string alg,const string algid,
    const AtomicType typ,const vector<ProcessingHistory*> parents,
      const bool create_newid=true);
```
Kind of a verbose name but it avoids the confusion of calling it reduce and makes the usage clear.   

I could see now way to avoid the clean_accumulate_uuids method.   That would need to be called on the result of a reduce function.   It is necessary, as the comments say, because if the operation gets fragmented between multiple processors I am pretty sure we could get multiple uuids, although that is not certain.   It may not be necessary, but we should try using it until proven otherwise.

**Comment by pavlis** [comment] 2020-10-17 11:31
I realized an important limitation on the algorithm I implemented for the clean_accumulate_uuids method described above.   A simple way to introduce this is to paste the (hopefully final) api definition with doxygen comments here:
```
  /* \brief Clean up inconsistent uuids that can be produced by reduce.

  In a spark reduce operation it is possible to create multiple uuid keys
  for inputs to the same algorithm instance.  That happpens because
  the mechanism used by ProcessingHistory to define the process history
  tree is not associative.   When a reduce gets sprayed across multiple
  nodes multiple initializations can occur that make artifical
  inconsitent uuids.  This method should normally be called after a reduce
  operator if history is being preserved or the history chain may be
  foobarred - no invalid just mess up with extra branches in the processing
  tree.   This algorithm uses matching ald and algid to define duplicates.
  A VERY IMPORTANT limitation of that is that algid MUST be unique for a
  given job run when a reduce is called.  i.e. if an earlier workflow had
  used alg and algid but with a different jobid and jobname the distintion
  cannot be detected with this algorithm.   This means our global history
  handling must guarantee algid is unique for each run.

  \param alg is the algorithm field to test for duplicates
  \param algid is the algorithm id file to test for duplicates.

  \return unique uuid for alg,algid match set in the history chain.
    Note if there are not duplicates it simply returns the only one it finds.
    If there are duplicates it returns the lexically smallest (first in
    alphabetic order) uuid.  Most importantly if there is no match or if
    history is empty it returns the string UNDEFINED.  
  */
  string clean_accumulate_uuids(const string alg, const string algid);
```
The key point was that unless we want to modify the NodeData structure to include "job" data (jobid and jobname), which I think ill advised as it adds unnecessary memory bloating, any reduce operation must be careful to assure the combination of algorithm and algorithm id is unique for every occurrence.   With our model that would be automatic for a single workflow, BUT if a workflow were made up of multiple runs (the norm) the algid would need to be coordinated between runs.   If we continue that restriction it will complicate our (planned) global processing history manager.  I think the cost of that is small compared to the unnecessary memory bloat that would be required if we add "job" data to the NodeData structure.   We should all remember this and try not to forget this limitation or it could bite is down the road.

**Comment by wangyinz** [comment] 2020-10-18 07:01
Yes, I think the original design of separating job-level history from objects is good. I think the algid is unique within a job by design. Our implementation with uuid guarantees that anyway.

**Comment by pavlis** [comment] 2020-10-18 10:10
I want to clarify this as you clearly misunderstood.   As you know the problem is that in a reduce operation multiple, independent processes could initiate a reduce operator.   e.g., as I understand it if the reduce were being don by 3 nodes the reduce might begin with passing the first 6 objects with two to each node.   Suppose it is a sum they would each compute a+b and return the result.  After the first pass there are now 3 sums.  After that what happens isn't an issue, but what happens if initialization of the sum splits like that is each processors initial a+b result will be initialized with a new uuid.    Then the 3 (in this example) node results are summed to produce the final answer the result will have 3 chains defined by 3 uuids for each node rather than one that would properly define the process tree.   

The clean_accumulate_uuids solves this problem by scanning the container containing the node data to search for all nodes created by algorithm:algid.   Where trouble could occur is if we had two workflows that, for example, had a stack operation (common).   Suppose two successive work flows defined history by defining algorithm='stack' and algid='1' (for example).   If any data passes through both instances of this stack operator, clean_accumulate_uuids will clobber the history tree.   

Hopefully that clarifies why our global process manager will need to assure the algid is unique.   Perhaps you are thinking of a solution.  That is, the global process manager should use something like the objectid of the parameter definitions saved in mongo or a uuid generated from a random number generator (like ProcessingHistory)   to define algid.

**Comment by pavlis** [comment] 2020-10-18 18:21
I just checked in a revision to ccore that fixes the problem with reduce - at least it should if my theoretical understanding of how reduce behaves is correct.   Implementing a stack function in python is the next step, but part of the test may not be possible without running  large stack.  i.e. the issue that required clean_accumulate_uuids will only arise if spark fragments the reduce and I don't think that is totally predictable. 

IMPORTANT change is as I was debugging this I realized the api definition for clean_accumulate_uuids was dump.  It did not actually need any arguments.  i.e. the prototype is now:
```
string clean_accumulate_uuids();
```
where it still returns the unique uuid it set of the previous reduce operator.

**Comment by wangyinz** [comment] 2020-10-19 07:07
Aha, thanks for clarifying! I see what the potential issue is. I guess we didn't guarantee `algid` unique in our original design. The `algid` is supposed to be defined by the input parameters, and if the same procedure is done multiple times in a job, that will cause the collision... 

One solution that requires no change to the new interface you defined here is that we might tag the `algid` of nodes in `ProcessingHistory::accumulate` as something like `algid.temp`. Then, in `ProcessingHistory::clean_accumulate_uuids`, we can let it only manipulate the nodes whose `algid` field ends with "temp". After the clean is done, we can then remove the "temp" in `algid`. This is basically introducing a temporary stage for nodes involved within a reduce call. We use `ProcessingHistory::accumulate` to mark all nodes entered the temporary stage, and then clean up and realize the nodes with `ProcessingHistory::clean_accumulate_uuids`. This way, the `algid` will always be unique within a reduce call. The only caveat is that if `clean_accumulate_uuids` is not correctly called after a reduce, the history will be screwed up. But current implementation has the same issue, and we will be dealing the history within a wrapper for the reduce functions we define, so I guess that is not a big problem.

**Comment by wangyinz** [comment] 2020-10-19 07:09
p.s. I fixed the python test and added some tests for the new accumulate call in https://github.com/wangyinz/mspass/commit/47c59b50f58f0c4b1b06b2fdc06f569cee02210b.

**Comment by pavlis** [comment] 2020-10-19 08:50
I'm not sure in the comment above how the "temp" field you suggest adding could be done to be guaranteed unique and consistent across multiple nodes?   Could you clarify?

My thoughts on this are to handle this with the global processing history mechanism.   The algid is just a string so one extreme possibility is have the algid created as a uuid using the init model we have discussed previously.   In any case, I don't think this is an extremely difficult problem as long as we don't forget this.  We should try to make sure user's don't need to handle this bookkeeping themselves or it will bite people.

**Comment by wangyinz** [comment] 2020-10-19 15:36
This is what I mean: https://github.com/wangyinz/mspass/commit/3dd98ad88da15679e2b2a62cae5dcaa3a4e5b2f4.

Basically, the `algid` created by `accumulate` will end with a ".acc", which will be identified in `clean_accumulate_uuids` and removed. I added a test that intentionally use a alg name and id that collides with previous nodes:
https://github.com/wangyinz/mspass/blob/3dd98ad88da15679e2b2a62cae5dcaa3a4e5b2f4/python/tests/test_ccore.py#L522-L536
It seems to be working as expected. Note that this test would fail in the old implementation.

**Comment by pavlis** [comment] 2020-10-19 17:18
Ahh, I get you now.  That would be a minor change compared to what I had to do to make accumulate work.

There is a very similar test to what you give in the C++ test program tests/history/test_history so I would have been real surprised if that hadn't worked as expected.

**Comment by wangyinz** [comment] 2020-10-19 22:00
I made a wrong statement earlier. This interface will require users call `clean_accumulate_uuids` after any reduce calls, and it can't be done within a wrapper.

So, I spend a bit more time on this and found that our `accumulate` implementation could be more straightforward. Instead of relying on the `add_one_input` method, I defined a similar `merge` method that merges the parent nodes of "current" of two history object here: https://github.com/wangyinz/mspass/commit/6438f4b943537ae84e17d1a75c9e9ce0f1914e32

With this new implementation, there is no need to call `clean_accumulate_uuids` because the new merge will not introduce a new level to the history tree. The only caveat is that if two accumulates on the same `algname` and `algid` are called immediately after each other, the history will be incorrectly merged... Not sure there is a way to resolve this problem without defining an additional step like what I did earlier.

**Comment by pavlis** [comment] 2020-10-20 08:58
I think I understand what you did and it makes sense.   

Three residual questions:
1.  You state thre is no need to call clean_accmulate_uuids.   If so, can we eliminate that method?   It is currently still in the .h and .cc files.
2. I didn't notice if you added test code for this revision, but presume you did.   When 1 is answered I can and should revised test_history.cc.   
3.  Can merge be private?   The use seems completely internal.

**Comment by wangyinz** [comment] 2020-10-20 15:53
Yes, it can be removed. Actually I already removed it from our python interface. I leave the code in C there because I am thinking that we might provide both mechanisms as options. The user can choose to use the new accumulate method or the old one. They will need to make sure two reductions of the same `algname` and `algid` won't be following each other in the former, or they can choose the other option and do the clean-up afterwards. Not sure if more options is good though...

I didn't add new test, and actually removed part of the python test I showed earlier because of the new limitation. But, the old `test_history.cc` works perfectly with the new accumulate, and that's actually the test I use to verify the new implementation. If we decide to remove the `clean_accumulate_uuids`, then we will need to revise the `test_history.cc` and remove the calls there.

Yes, it make sense to be private, and I already defined it as `_merge` in the python interface. I didn't do the same to the C++ code because I think this method might be useful when manipulating the history records (for users who knows what they are doing).

**Comment by pavlis** [comment] 2020-10-21 09:06
I think I'll just leave this all alone for now then.   I'll leave this issue open because we still need to implement stack and we could find other issues when we actually do that.

**Comment by JiaoMaWHU** [comment] 2020-10-25 04:14
I finished the stack function in this pull request: https://github.com/wangyinz/mspass/pull/75. The bug "reduce module not found" is solved. Previously I was using the relative path to import the reduce module, however, it may trigger some errors, I solved it by directly using the mspass library.

**Comment by JiaoMaWHU** [comment] 2020-10-26 00:44
merged: https://github.com/wangyinz/mspass/pull/75

**Comment by JiaoMaWHU** [comment] 2020-10-26 00:45
merged https://github.com/wangyinz/mspass/pull/75

**Closed by JiaoMaWHU** 2020-10-26 00:45 UTC
